# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f71129e86d793fc92820cff60614643d6ae7821c3f533545cbd6d5760a8109a2d7fec379f16f2f39f3af64eaf72b96f206b80c176a1397243f4a95048d9de4a

test:
  secret_key_base: a6dd27d1d6bf742ef4393d17aa9b166b3c710a0ef52ced0ba2d02378845a1047c6b891d80f9daf1eaab0d85d7eba5729236ff3b581fa05abef844c7d30a4c35b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
